---
- name: week5 task
  hosts: all
  tasks:
  
  
  
    - name: Copy a single file where the source is on the remote host
      win_copy:
       src: C:\Temp\foo.txt
       dest: C:\ansible\foo.txt
       remote_src: yes
       
    - win_lineinfile:
        path: c:\Temp\renamed.text
        regexp: '^name='
        line: 'name=JohnDoe'
       
       
    - name: Create a new group
      win_group:
        name: deploy
        description: Deploy Group
        state: present 
    
    - name: Ensure user bob is present
      win_user:
        name: bob
        state: present
        
     
