---
- name: week5 task
  hosts: all
  tasks:
  
  
  
    - name: Copy a single file
      win_copy:
        src: /srv/myfiles/foo.conf
        dest: c:\Temp\renamed-foo.conf
       
    - win_lineinfile:
        path: c:\Temp\renamed-foo.conf
        regexp: '^name='
        line: 'name=JohnDoe'
       
       
    - name: Create a new group
      win_group:
        name: deploy
        description: Deploy Group
        state: present 
    
    - name: Ensure user bob is present
      win_user:
        name: bob
        state: present
        
     
