---
- name: week5 
  hosts: all
  tasks:
   - name: Set timezone to 'GMT Standard Time' (GMT)
     win_timezone:
       timezone: GMT Standard Time
   - win_updates:
     category_names:
        - Application
        - Updates
   - name: Install git
     win_chocolatey:
       name:
         - git
         - notepadplusplus
       state: present
