---
- name: week5 
  hosts: all
  tasks:
   - name: Set timezone to 'GMT Standard Time' (GMT)
     win_timezone:
       timezone: GMT Standard Time
   - name: Choose which Windows updates to install
     win_updates:
       category_names:
         - SecurityUpdates
         - CriticalUpdates
         - UpdateRollups
       reboot: yes
   - name: Install git
     win_chocolatey:
       name: git
       state: present

   - name: Upgrade installed packages
     win_chocolatey:
       name: all
       state: latest

   - name: Install notepadplusplus version 6.6
     win_chocolatey:
      name: notepadplusplus.install
      version: '6.6'
