- hosts: all
  tasks:
  - name: Playbook
    win_ping:
    register: myconfig
    
  - debug:
     var: myconfig
  
  - name: Copy a single file
    win_copy:
      src: hello.txt
      dest: C:\Users\Administrator\Desktop\

  - name: Find files in path
    win_find:
       paths: C:\Users\Administrator\Desktop\
      
  - name: Updating the content
    win_lineinfile:
       path: C:\Users\Administrator\Desktop\hello.txt
       regex: 'hi'
       line: 'Hello'

  - name: Create a new group
    win_group:
       name: User
       description: 'Users Group '
       state: present     

  - name: Ensure user  is present
    win_user:
       name: Sayali
       password: 1
       state: present
       groups:
          - Userpath: C:\Users\Administrator\Desktop\hello.txt
       regex: 'hi'
       line: 'Hello '

  - name: Create a new group
    win_group:
       name: User
       description: 'Users Group'
       state: present     

  - name: Ensure user is present
    win_user:
       name: sayali
       password: 1
       state: present
       groups:
          - User

